female(tamil).
female(sita).
female(anu).
female(pavi).
female(agalya).
female(preeti).
male(ram).
male(damodar).
male(ramesh).
male(ravi).
male(udhay).
male(kishore).
father(ram,udhay).
father(ram,preeti).
father(damodar,ram).
father(damodar,ravi).
father(ramesh,tamil).
father(ramesh,anu).
mom(tamil,preeti).
mom(tamil,udhay).
mom(agalya,ram).
mom(agalya,ravi).
mom(sita,tamil).
mom(sita,anu).
spouse(ram,tamil).
spouse(tamil,ram).
spouse(damodar,agalya).
spouse(agalya,damodar).
spouse(ramesh,sita).
spouse(sita,ramesh).
spouse(ravi,pavi).
spouse(pavi,ravi).
spouse(kishore,anu).
spouse(anu,kishore).

child(X,Y):-(male(X);female(X)),(father(Y,X);mom(Y,X)).
daughter(X,Y):-female(X),(father(Y,X);mom(Y,X)).
mother(X,Y):-female(X),child(Y,X).
sibling(X,Y):-mom(A,X),mom(A,Y).
brother(X,Y):-male(X),father(A,X),father(A,Y).
sister(X,Y):-female(X),mom(A,X),mom(A,Y).
grandparent(X,Y):-child(A,X),child(Y,A).
grandmother(X,Y):-female(X),child(A,X),child(Y,A).
uncle(X,Y):- male(X),child(X,Z),child(A,Z),child(Y,A).
sister_in_law(X,Y):-
female(X),child(Y,A),child(Z,A),spouse(X,Z);female(X),child(X,A),child(Z,A),spouse(Y,Z).
mother_in_law(X,Y):-female(X),spouse(Y,Z),child(Z,X).
wife(X,Y):-female(X),spouse(X,Y).
ancestor(X,Y):-child(Y,X);child(A,X),child(Y,A).
descendant(X,Y):-child(X,Y);child(X,A),child(A,Y).
relative_by_blood(X,Y):-
child(Y,X);child(X,Y);child(A,X),child(Y,A);child(A,Y),child(X,A);child(X,A),child(Y,A).